### ISSUE TITLE
chat entity, repository를 생성한다.

### ISSUE THREAD

**Issue by rlarltj** [prgrms-web-devcourse/Team-Kkini-Mukvengers-BE#108]
### 🚀 목적
- 각 채팅방에 접속했을 때 이전의 채팅 내용들을 조회할 수 있어야 합니다.
- 모든 채팅을 DB에 저장합니다.

### 🔗 작업
- Chat Entity 생성 및 validation(글자 수 등)
- Chat Repository 생성

### ✅ 완료조건
- 채팅방에 입장 시 이전 채팅기록을 조회할 수 있다.

**Comment by JoosungKwon** [comment]
하나의 이슈로 관리하기 위해서 닫겠습니다~!
